name: Tagify Backend test & deploy

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17.2
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: 1234
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U test -d test_db"
          --health-interval=5s
          --health-timeout=3s
          --health-retries=5

    env:
      DATABASE_URL: postgresql+asyncpg://test:1234@localhost:5432/test_db
      TEST_GOOGLE_ID_TOKEN: ${{ secrets.TEST_GOOGLE_ID_TOKEN }}
      TEST_GOOGLE_OAUTH_ID: ${{ secrets.TEST_GOOGLE_OAUTH_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          cd server
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd server
          pytest -v --maxfail=1

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/work/b_Tagify
            git pull origin main
            docker compose down
            docker compose up -d --build
